### ISSUE TITLE
Incluir tutorial de instalação do Oracle XE

### ISSUE THREAD

**Issue by marlonbernardes** [CWISoftware/crescer-2015-1#1]
Como o Oracle XE será utilizado durante as aulas, seria interessante incluir um tutorial de instalação no README do projeto.

**Comment by nunes-andre** [comment]
A instalação é simples. Next > Next > Finish.

**Comment by marlonbernardes** [comment]
@nunes-andre É mesmo? Eu achava que precisava incluir umas variáveis de ambiente também (tipo ORACLE_HOME, NLS_LANG, etc). Enfim, melhor assim. Quando eu atualizar o README com as instruções de instalação fecho essa issue!

**Comment by marlonbernardes** [comment]
Coloquei o tutorial de instalação no README.
